"""Emit the compiled-in data of parts 001, 002, 005 and 006 as Pascal typed
constants, the same way tools/emit_pascal_data.py does for part 003.

Anything in DGROUP's *initialised* region was a typed constant in the original
source. Plain `var` lands in BSS and is not stored in the executable, so
whatever we can read out of the file image must have carried an initialiser.

DGROUP is always the highest segment in the relocation map:

    part 001  $18F8      part 002  $1866      part 003  $1761
    part 005  $166C      part 006  $164E

Output goes to src/gen/ and is included by the hand-written units.
"""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
# mzinfo is the kit's now (#50). These scripts are the record's, or are
# waiting their turn to move, and they keep working meanwhile -- which is
# the standing rule: the originals go on working until their successor has
# landed AND every caller has been repointed.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] /
                      "kit" / "tools"))
from substrate.mzinfo import parse

OUT = Path("src/gen")

DGROUP = {"001": 0x18F8, "002": 0x1866, "003": 0x1761,
          "005": 0x166C, "006": 0x164E}


def dg(part):
    h = parse(Path(f"work/split/NEUROSIS_{part}.exe"))
    return h["raw"], h["hdrsize"] + DGROUP[part] * 16 - 0x10000


def fmt(name, typ, values, per_line=12, conv=str, group=None):
    """Emit a Pascal typed-constant array.

    Multidimensional arrays need NESTED parentheses: `array[1..N, 1..3]` takes
    ((a,b,c), (d,e,f), ...), not a flat list. Getting this wrong is what
    produced `Error 88: "(" expected` the first time these reached TPC.
    Pass group=3 for [N,3]; group=(16,8) for [N,16,8].
    """
    lines = [f"  {name} : {typ} = ("]
    if group is None:
        for i in range(0, len(values), per_line):
            chunk = ", ".join(conv(v) for v in values[i:i + per_line])
            lines.append(f"    {chunk}" + ("," if i + per_line < len(values) else ""))
    elif isinstance(group, int):
        rows = [values[i:i + group] for i in range(0, len(values), group)]
        per = max(1, per_line // (group + 1))
        for i in range(0, len(rows), per):
            body = ", ".join("(" + ", ".join(conv(v) for v in r) + ")"
                             for r in rows[i:i + per])
            lines.append(f"    {body}" + ("," if i + per < len(rows) else ""))
    else:
        outer, inner = group
        blk = outer * inner
        for b in range(0, len(values), blk):
            rows = [values[b:b + blk][i:i + inner] for i in range(0, blk, inner)]
            lines.append("    (")
            for j, r in enumerate(rows):
                body = "(" + ", ".join(conv(v) for v in r) + ")"
                lines.append(f"      {body}" + ("," if j + 1 < len(rows) else ""))
            lines.append("    )" + ("," if b + blk < len(values) else ""))
    lines.append("  );")
    return "\n".join(lines)


def header(text):
    return "{ " + text.strip() + "\n\n  Generated by tools/emit_pascal_data2.py -- do not edit. }\n\ncons" + "t\n"


# ---------------------------------------------------------------- part 001

def emit_p001():
    raw, base = dg("001")
    out = [header("""Part 001 scene 5 -- the two 3-D vector objects.

  Compiled into DGROUP as signed integer (X, Y, Z) triples and converted to
  Real at load time by Math_IntToReal (1483:0000) into 12-byte records.

  VecLogoA is flat (Z = 0 throughout) -- the circled "A" logo mark.
  VecGlobe is three orthogonal rings, +/-50 on every axis.

  See assets/part001/vector_logo_a.png and vector_globe.png.""")]
    total = 0
    # VecRing sits BETWEEN the two and nothing reads it. It is 18 points of a
    # radius-50 circle in the YZ plane at 20-degree steps -- one of the globe's
    # three rings, emitted on its own. The loader reads the globe from $01A8
    # (12c5:08b3 is PUSH WORD PTR [DI+$1A8]), so these 108 bytes are never
    # touched at run time. They are in DGROUP all the same, and leaving them
    # out shifted every initialised byte after $013C.
    for name, off, n, note in (("VecLogoA", 0x001C, 48, "the circled A, Z = 0"),
                               ("VecRing",  0x013C, 18, "a YZ ring, radius 50 -- NEVER READ"),
                               ("VecGlobe", 0x01A8, 36, "three rings, +/-50")):
        vals = []
        for i in range(n):
            vals.extend(struct.unpack_from("<hhh", raw, base + off + i * 6))
        out.append(f"  {{ DS:${off:04X} -- {n} points, {note} }}")
        # THE FIRST DIMENSION IS ZERO-BASED, and the loader's fold displacement
        # says so exactly. VecGlobe sits at DS:$01A8 and 12c5:08b3 is
        # PUSH WORD PTR [DI+$1A8] with DI = I * 6 -- the folded displacement IS
        # the base, so the first subscript contributes nothing to it and its low
        # bound is 0. Emitted as array[1..n] the fold came out $1A2, one 6-byte
        # element low, and the loader carried an INC AX per point to compensate.
        # FLAT AND ZERO-BASED, and the ORDER OF THE TWO MULTIPLIES says so. The
        # loader scales its counter by six either way, but 12c5:08a6 does it as
        # MOV SI,AX / SHL AX,1 / ADD AX,SI -- times THREE -- and only then
        # MOV DI,AX / SHL DI,1, times two. A two-dimensional [I, 1] subscript
        # emits the halves the other way round (times two, then three), because
        # it scales by the element size and the element is three Integers. Times
        # three then two is an INDEX of I * 3 into a one-dimensional Integer
        # array, with the trailing SHL being the Integer stride.
        # The fold confirms it: VecGlobe is at DS:$01A8 and the displacement is
        # $1A8, $1AA, $1AC for the three components -- base plus 0, 2, 4, which
        # is `[I * 3]`, `[I * 3 + 1]`, `[I * 3 + 2]` with the constant folded in.
        # Same shape as the Vert* arrays emitted further down.
        out.append(fmt(name, f"array[0..{n * 3 - 1}] of Integer", vals, 9))
        total += len(vals)
    OUT.joinpath("P1VECT.INC").write_text("\n".join(out) + "\n", encoding="ascii")
    return total


# ---------------------------------------------------------------- part 002

P2_OBJECTS = [
    ("Enterprise", 0x0004, 75, 0x01C6, 55, "the USS Enterprise"),
    ("Revolver",   0x067E, 68, 0x0816, 64, "a revolver, modelled along Y"),
    ("Sailboat",   0x0B06, 32, 0x0BC6, 21, "a sailboat, modelled along Y"),
    ("Quad",       0x0CAE,  4, 0x0CC6,  1, "a single quad"),
]


def emit_p002():
    raw, base = dg("002")
    out = [header("""Part 002 scene 2 -- the four 3-D models, compiled into DGROUP.

  Vertices are signed word triples; coordinates are HALVED on load.

  The face stream is variable length -- for each face:

      count, index1 .. indexN, colour        (count + 2 words)

  Indices are stored zero-based and incremented on load. Faces have 3, 4, 6
  or 8 vertices. Scene2_Intro (108b:1bbd) is the loader.

  See assets/part002/obj_*.png -- five projections of each, because a model
  is often unrecognisable from the obvious X/Y view.""")]
    total = 0
    for name, voff, nv, foff, nf, note in P2_OBJECTS:
        verts = []
        for i in range(nv):
            verts.extend(struct.unpack_from("<hhh", raw, base + voff + i * 6))
        out.append(f"\n  {{ {note} -- vertices DS:${voff:04X} }}")
        # The counts are emitted rather than written into the loader by hand:
        # Scene2_Setup reads them back OUT of the object it just filled,
        # so the only place a literal belongs is beside the table it counts.
        out.append(f"  NVert{name} = {nv};")
        out.append(f"  NFace{name} = {nf};")
        # FLAT, and the loader indexes it [(I - 1) * 3 + k]. A two-dimensional
        # array was an improvement on a bare [I] and still not the shape: for
        # A[I - 1, 2] the compiler multiplies the outer index by SIX in one go
        # and folds the inner subscript into the displacement, while the
        # original multiplies by THREE, adds the inner offset AT RUNTIME -- one
        # INC per unit, so the third component is INC AX twice -- and only then
        # doubles for the element size. That is the code for an explicit
        # `(I - 1) * 3 + k` index into a one-dimensional array of Integer, and
        # the displacement left over is the table's own DGROUP offset.
        #
        # The bytes are identical either way; only the addressing differs. This
        # closed twelve spans in the four loaders, three per object.
        out.append(fmt(f"Vert{name}", f"array[0..{nv * 3 - 1}] of Integer", verts, 9))

        faces, p = [], 0
        for _ in range(nf):
            cnt = struct.unpack_from("<h", raw, base + foff + p * 2)[0]
            faces.append(cnt)
            for k in range(cnt + 1):
                faces.append(struct.unpack_from("<h", raw, base + foff + (p + 1 + k) * 2)[0])
            p += cnt + 2
        out.append(f"  {{ {nf} faces -- DS:${foff:04X}, {p} words }}")
        out.append(fmt(f"Face{name}", f"array[1..{p}] of Integer", faces, 12))
        total += len(verts) + len(faces)
    OUT.joinpath("P2OBJ.INC").write_text("\n".join(out) + "\n", encoding="ascii")
    return total


# ---------------------------------------------------------------- part 005

def emit_p005():
    raw, base = dg("005")
    tris = [struct.unpack_from("<HHH", raw, base + 2 + i * 6) for i in range(1922)]
    flat = [v for t in tris for v in t]
    body = header("""Part 005 -- the mesh triangle list.

  A 32 x 32 vertex grid (indices 0..1023) triangulated into 1,922 triangles:
  each of the 31 x 31 quads becomes the pair

      (n, n+1, n+32)  and  (n+1, n+33, n+32)

  The list is compiled in rather than generated, so the renderer walks it
  directly. DS:$0002 .. $2D0D.""")
    body += fmt("MeshTris", "array[1..1922, 1..3] of Word", flat, 12, group=3)
    OUT.joinpath("P5MESH.INC").write_text(body + "\n", encoding="ascii")
    return len(flat)


# ---------------------------------------------------------------- part 006

# P6S4 declares `Lines = 113` and indexes String[12]; the generator must
# agree with the source it feeds, so both live here as names rather than
# being derived from however much text the image happens to hold.
P6_CREDIT_LINES = 99       # NOT 113 -- see the docstring below
P6_CREDIT_WIDTH = 255      # 256 bytes per element, and the docstring below
                           # always said so -- a Borland String[n] occupies
                           # n+1 bytes, so the $100 stride this table is READ
                           # with IS the declaration. Declared String[12] the
                           # stride was 13 and the array was 1,469 bytes where
                           # the original's is 28,928.


def pascal_strings(raw, base, first, stride, limit=400):
    out, off = [], first
    while len(out) < limit:
        n = raw[base + off]
        if n == 0 or n > 80:
            break
        out.append(raw[base + off + 1: base + off + 1 + n].decode("latin1"))
        off += stride
    return out


def emit_p006_text():
    """The credits table -- NINETY-NINE entries of 256 bytes from DS:$0D8A.

    This docstring used to say 113, and 113 is the LOOP'S bound, not the
    array's. The two are not the same and the address of the next variable
    proves it: P6S1's Path pointer is at DS:$737E, and 99 slots of 256 from
    $0D8A end at $708A while 113 would run to $7F8A -- with Path inside the
    array. It cannot be 113.

    P6S4 does count to 113 (11bb:02fa stops at $72), so lines 100..113 read
    PAST the array into the constants beyond it, which are zeros. That is why
    they arrive blank at run time, and it is the observation the old docstring
    had hold of by the wrong end.

    The stride is $100, so the element type is String[255]: a Borland
    String[n] occupies n+1 bytes. Declared String[12] the table came out 1,469
    bytes where the original's is 25,344.
    """
    raw, base = dg("006")
    lines = pascal_strings(raw, base, 0x0D8A, 0x0100, limit=P6_CREDIT_LINES)
    blank = ""             # the trailing slots are ZEROS in the image, which
                           # is a String of length 0, not a run of spaces
    lines += [blank] * (P6_CREDIT_LINES - len(lines))
    body = header(f"""Part 006 scene 4 -- the credits text.

  A Borland `array[1..{P6_CREDIT_LINES}] of String[{P6_CREDIT_WIDTH}]` at DS:$0D8A, 256 bytes
  per element, which is why the stride in DGROUP is $100. Only the first
  {sum(1 for s in lines if s.strip())} lines carry text in the load image; the rest fall past its end
  and are blank at run time, so they are blank here.

  Four blocks, one per member: EzE, GoTH, Denthor and Fubar.

  Generated by tools/emit_pascal_data2.py -- do not edit.""")
    body += "  CreditText : array[1..%d] of String[%d] = (\n" % (
        P6_CREDIT_LINES, P6_CREDIT_WIDTH)
    for i, s in enumerate(lines):
        comma = "," if i + 1 < len(lines) else ""
        body += f"    '{s.replace(chr(39), chr(39) * 2)}'{comma}\n"
    body += "  );\n"
    OUT.joinpath("P6TEXT.INC").write_text(body, encoding="ascii")
    return len(lines)


def emit_p006_cells():
    """The whoosh board: array[1..27, 1..16, 1..8] of Byte.

    Stored [band][column][rowInBand]; each band is one 8-wide x 16-tall letter
    lying on its side, because the board is drawn transposed (map row -> screen
    X, map column -> screen Y).
    """
    raw, base = dg("006")
    A = 0x000A
    # TWENTY-SEVEN BANDS, and DGROUP's own arithmetic is what fixes the count:
    # the credits text starts at DS:$0D8A in the 1994 file, and $000A plus
    # 27 * 128 is $0D8A exactly, where 26 bands land it at $0D0A. The
    # twenty-seventh is all zeroes, which is why nothing in the data itself
    # gives it away -- it took the two DGROUP images side by side, where the
    # original has 128 more zeros before the first credit string than ours did.
    # Worth 128 bytes to every variable in the part, and the part's data was
    # 128 bytes short of the original's until it was counted.
    vals = list(raw[base + A: base + A + 27 * 128])
    body = header("""Part 006 scene 2 -- the whoosh board.

  array[1..27, 1..16, 1..8] of Byte, DS:$000A. Each band is one letter cell
  block; the value is the CELL TYPE drawn at that grid position (1 = letter,
  0 = nothing; Whoosh_Load pre-fills the whole board with 2 = background).

  The storage is [band][column][rowInBand], and the board is drawn transposed
  -- map row becomes screen X, map column becomes screen Y -- so each band is
  an 8-wide by 16-tall letter lying on its side.

  Bands  1..16 spell "ASPHYXIA RULZ" (13 letters then 3 blanks) and are the
                only ones Whoosh_Load copies onto the board.
  Bands 17..26 spell "0,000 DOTS" and are NEVER USED -- dead data left in the
                executable. The scroll text boasts "4000 DOTS", so this was
                presumably an earlier version of the same gag.
  Band     27 is entirely ZERO and is never drawn either. It is here because
                the credits text that follows it in DGROUP is at $0D8A, and
                $000A + 27 * 128 is $0D8A; twenty-six bands put every variable
                in the part 128 bytes low.""")
    # CELLSHAPE, and all TWENTY-SEVEN bands. The truncated 16-band copy in
    # P6SHAPE.INC was read from the same DS:$000A with a shorter length, and
    # its own generator no longer exists. Bands 17..27 are never drawn -- the
    # same shape as part 003's unused shape slots -- but they are in DGROUP
    # and everything declared after them moves if they are left out.
    body += fmt("CellShape", "array[1..27, 1..16, 1..8] of Byte", vals, 32, group=(16, 8))
    OUT.joinpath("P6CELL.INC").write_text(body + "\n", encoding="ascii")
    return len(vals)


# ---------------------------------------------------------------- part 003

def emit_p003_captions():
    raw, base = dg("003")
    lines = pascal_strings(raw, base, 0x76B8, 0x0100)
    body = header(f"""Part 003 scene 7 -- the member captions, {len(lines)} lines.

  array[1..4, 1..10] of String[255], DS:$76B8, stride $100. Ten lines per
  member, in the same order as the four rotating portraits.
  TWO-DIMENSIONAL, and 125e:0741 is why. The original indexes it as
  Captions[N, Row][Col]: IMUL DI,[BP+4],$0A00 for the member, a separate
  Row*256, and Col added last. A flat array[1..40] indexed
  Captions[(N-1)*10 + Row] emits a DEC and an IMUL by 10 instead -- the same
  address by a different route, because the displacement absorbs the
  difference, so the bytes never match. Same 10,240 bytes either way.


  STRING[255], AND THE STRIDE THIS TABLE IS READ WITH IS WHY. A Borland
  String[n] occupies n+1 bytes, so $100 is String[255]; the declaration used to
  say String[50], a stride of 51. Across forty slots that is 8,200 bytes, and
  it was the whole of this part's remaining DGROUP size difference.

  The unused tail of each slot is zeros, and they are STORED -- a typed
  constant is in the file image and a var is not. Nothing in the part's code
  reads them: a scan of every code segment for absolute displacements into that
  range found nine scalars at the very top and nothing across the eight
  kilobytes below.""")
    rows = 10
    members = len(lines) // rows
    body += ("  Captions : array[1..%d, 1..%d] of String[255] = ("
             + "\n") % (members, rows)
    for m in range(members):
        body += "    (" + "\n"
        for r in range(rows):
            s = lines[m * rows + r]
            comma = "," if r + 1 < rows else ""
            body += "      '%s'%s" % (s, comma) + "\n"
        body += "    )%s" % ("," if m + 1 < members else "") + "\n"
    body += "  );" + "\n"
    OUT.joinpath("P3CAPT.INC").write_text(body, encoding="ascii")
    return len(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    results = [
        ("P1VECT.INC", emit_p001(), "values"),
        ("P2OBJ.INC", emit_p002(), "values"),
        ("P5MESH.INC", emit_p005(), "values"),
        ("P6TEXT.INC", emit_p006_text(), "strings"),
        ("P6CELL.INC", emit_p006_cells(), "bytes"),
        ("P3CAPT.INC", emit_p003_captions(), "strings"),
    ]
    for name, n, unit in results:
        p = OUT / name
        print(f"  {name:<14} {n:>7,} {unit:<8} {len(p.read_text(encoding="ascii", errors="replace").splitlines()):>6,} lines")


if __name__ == "__main__":
    main()
