"""Emit compiled-in data back out as Borland Pascal typed constants.

Anything the demo keeps in DGROUP's *initialised* region was a typed constant
in the original source -- `const X : T = (...)`. Plain `var` lands in BSS and is
not stored in the executable at all, so data we can read out of the file image
must have been declared with an initialiser.

This matters for the reconstruction: without these declarations the source is a
skeleton that would compile to a different binary. Output goes to src/gen/ and
is included by the hand-written units.
"""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mzinfo import parse

OUT = Path("src/gen")
PER_LINE = 12


def dgroup_base(part, seg):
    h = parse(Path(f"work/split/NEUROSIS_{part}.exe"))
    return h["raw"], h["hdrsize"] + seg * 16 - 0x10000


def fmt_array(name, typ, values, per_line=PER_LINE, hexfmt=False, group=None):
    """Multidimensional arrays need NESTED parens -- see the note in
    tools/emit_pascal_data2.py. group=3 emits ((x, y, z), ...)."""
    def one(v):
        return f"${v:04X}" if hexfmt else str(v)

    lines = [f"  {name} : {typ} = ("]
    if group is None:
        for i in range(0, len(values), per_line):
            body = ", ".join(one(v) for v in values[i:i + per_line])
            lines.append(f"    {body}" + ("," if i + per_line < len(values) else ""))
    else:
        rows = [values[i:i + group] for i in range(0, len(values), group)]
        per = max(1, per_line // (group + 1))
        for i in range(0, len(rows), per):
            body = ", ".join("(" + ", ".join(one(v) for v in r) + ")"
                             for r in rows[i:i + per])
            lines.append(f"    {body}" + ("," if i + per < len(rows) else ""))
    lines.append("  );")
    return "\n".join(lines)


def emit_palette():
    raw, base = dgroup_base("003", 0x1761)
    parts = []
    for name, off in (("Red", 0x0002), ("Green", 0x00E3), ("Blue", 0x01C4)):
        vals = list(raw[base + off:base + off + 225])
        parts.append(f"  {{ DS:${off:04X} }}")
        parts.append(fmt_array(name, "TColourTable", vals))
    body = "\n".join(parts)
    OUT.joinpath("P3PAL.INC").write_text(
        "{ Tunnel palette -- three separate 225-byte channel tables.\n"
        "  Typed constants, so they live in the executable's initialised data\n"
        "  and are writable: the band rotations shuffle them in place.\n"
        "  Generated by tools/emit_pascal_data.py -- do not edit. }\n\n"
        "const\n" + body + "\n", encoding="ascii")
    return 675


def emit_sine():
    raw, base = dgroup_base("003", 0x1761)
    vals = [struct.unpack_from("<h", raw, base + 0x02A8 + i * 2)[0] for i in range(450)]
    OUT.joinpath("P3SINE.INC").write_text(
        "{ Sine table, 16.14 fixed point (x16384), 450 entries.\n"
        "  450 rather than 360 because cos(a) is read as sin(a+90) from the\n"
        "  same table -- see Morph_SetAngles.\n"
        "  Generated by tools/emit_pascal_data.py -- do not edit. }\n\n"
        "const\n" + fmt_array("SinTab", "array[0..449] of Integer", vals, 10) + "\n",
        encoding="ascii")
    return 450


def emit_shapes():
    raw, base = dgroup_base("003", 0x1761)
    out = ["{ Scene 3 morph shapes: 765 points of (X, Y, Z) signed words.",
           "  Generated by tools/emit_pascal_data.py -- do not edit. }", "",
           "const"]
    total = 0
    for name, off in (("Sphere", 0x0636), ("Cube", 0x5136), ("Grid", 0x63F6)):
        vals = []
        for i in range(765):
            vals.extend(struct.unpack_from("<hhh", raw, base + off + i * 6))
        out.append(f"  {{ DS:${off:04X} }}")
        out.append(fmt_array(f"Shape{name}", "TShape", vals, 9, group=3))
        total += len(vals)
    OUT.joinpath("P3SHAPE.INC").write_text("\n".join(out) + "\n", encoding="ascii")
    return total


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    n1, n2, n3 = emit_palette(), emit_sine(), emit_shapes()
    for f in sorted(OUT.iterdir()):
        print(f"{f}  {len(f.read_text().splitlines()):>5} lines")
    print(f"\n{n1 + n2 + n3:,} values emitted")


if __name__ == "__main__":
    main()
