"""Emit the compiled-in data of parts 001, 002, 005 and 006 as Pascal typed
constants, the same way tools/emit_pascal_data.py does for part 003.

Anything in DGROUP's *initialised* region was a typed constant in the original
source. Plain `var` lands in BSS and is not stored in the executable, so
whatever we can read out of the file image must have carried an initialiser.

DGROUP is always the highest segment in the relocation map:

    part 001  $18F8      part 002  $1866      part 003  $1761
    part 005  $166C      part 006  $164E

Output goes to src/gen/ and is included by the hand-written units.
"""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mzinfo import parse

OUT = Path("src/gen")

DGROUP = {"001": 0x18F8, "002": 0x1866, "003": 0x1761,
          "005": 0x166C, "006": 0x164E}


def dg(part):
    h = parse(Path(f"work/split/NEUROSIS_{part}.exe"))
    return h["raw"], h["hdrsize"] + DGROUP[part] * 16 - 0x10000


def fmt(name, typ, values, per_line=12, conv=str, group=None):
    """Emit a Pascal typed-constant array.

    Multidimensional arrays need NESTED parentheses: `array[1..N, 1..3]` takes
    ((a,b,c), (d,e,f), ...), not a flat list. Getting this wrong is what
    produced `Error 88: "(" expected` the first time these reached TPC.
    Pass group=3 for [N,3]; group=(16,8) for [N,16,8].
    """
    lines = [f"  {name} : {typ} = ("]
    if group is None:
        for i in range(0, len(values), per_line):
            chunk = ", ".join(conv(v) for v in values[i:i + per_line])
            lines.append(f"    {chunk}" + ("," if i + per_line < len(values) else ""))
    elif isinstance(group, int):
        rows = [values[i:i + group] for i in range(0, len(values), group)]
        per = max(1, per_line // (group + 1))
        for i in range(0, len(rows), per):
            body = ", ".join("(" + ", ".join(conv(v) for v in r) + ")"
                             for r in rows[i:i + per])
            lines.append(f"    {body}" + ("," if i + per < len(rows) else ""))
    else:
        outer, inner = group
        blk = outer * inner
        for b in range(0, len(values), blk):
            rows = [values[b:b + blk][i:i + inner] for i in range(0, blk, inner)]
            lines.append("    (")
            for j, r in enumerate(rows):
                body = "(" + ", ".join(conv(v) for v in r) + ")"
                lines.append(f"      {body}" + ("," if j + 1 < len(rows) else ""))
            lines.append("    )" + ("," if b + blk < len(values) else ""))
    lines.append("  );")
    return "\n".join(lines)


def header(text):
    return "{ " + text.strip() + "\n\n  Generated by tools/emit_pascal_data2.py -- do not edit. }\n\ncons" + "t\n"


# ---------------------------------------------------------------- part 001

def emit_p001():
    raw, base = dg("001")
    out = [header("""Part 001 scene 5 -- the two 3-D vector objects.

  Compiled into DGROUP as signed integer (X, Y, Z) triples and converted to
  Real at load time by Math_IntToReal (1483:0000) into 12-byte records.

  VecLogoA is flat (Z = 0 throughout) -- the circled "A" logo mark.
  VecGlobe is three orthogonal rings, +/-50 on every axis.

  See assets/part001/vector_logo_a.png and vector_globe.png.""")]
    total = 0
    for name, off, n, note in (("VecLogoA", 0x001C, 48, "the circled A, Z = 0"),
                               ("VecGlobe", 0x01A8, 36, "three rings, +/-50")):
        vals = []
        for i in range(n):
            vals.extend(struct.unpack_from("<hhh", raw, base + off + i * 6))
        out.append(f"  {{ DS:${off:04X} -- {n} points, {note} }}")
        out.append(fmt(name, f"array[1..{n}, 1..3] of Integer", vals, 9, group=3))
        total += len(vals)
    OUT.joinpath("P1VECT.INC").write_text("\n".join(out) + "\n", encoding="ascii")
    return total


# ---------------------------------------------------------------- part 002

P2_OBJECTS = [
    ("Enterprise", 0x0004, 75, 0x01C6, 55, "the USS Enterprise"),
    ("Revolver",   0x067E, 68, 0x0816, 64, "a revolver, modelled along Y"),
    ("Sailboat",   0x0B06, 32, 0x0BC6, 21, "a sailboat, modelled along Y"),
    ("Quad",       0x0CAE,  4, 0x0CC6,  1, "a single quad"),
]


def emit_p002():
    raw, base = dg("002")
    out = [header("""Part 002 scene 2 -- the four 3-D models, compiled into DGROUP.

  Vertices are signed word triples; coordinates are HALVED on load.

  The face stream is variable length -- for each face:

      count, index1 .. indexN, colour        (count + 2 words)

  Indices are stored zero-based and incremented on load. Faces have 3, 4, 6
  or 8 vertices. Scene2_Intro (108b:1bbd) is the loader.

  See assets/part002/obj_*.png -- five projections of each, because a model
  is often unrecognisable from the obvious X/Y view.""")]
    total = 0
    for name, voff, nv, foff, nf, note in P2_OBJECTS:
        verts = []
        for i in range(nv):
            verts.extend(struct.unpack_from("<hhh", raw, base + voff + i * 6))
        out.append(f"\n  {{ {note} -- vertices DS:${voff:04X} }}")
        out.append(fmt(f"Vert{name}", f"array[1..{nv}, 1..3] of Integer", verts, 9, group=3))

        faces, p = [], 0
        for _ in range(nf):
            cnt = struct.unpack_from("<h", raw, base + foff + p * 2)[0]
            faces.append(cnt)
            for k in range(cnt + 1):
                faces.append(struct.unpack_from("<h", raw, base + foff + (p + 1 + k) * 2)[0])
            p += cnt + 2
        out.append(f"  {{ {nf} faces -- DS:${foff:04X}, {p} words }}")
        out.append(fmt(f"Face{name}", f"array[1..{p}] of Integer", faces, 12))
        total += len(verts) + len(faces)
    OUT.joinpath("P2OBJ.INC").write_text("\n".join(out) + "\n", encoding="ascii")
    return total


# ---------------------------------------------------------------- part 005

def emit_p005():
    raw, base = dg("005")
    tris = [struct.unpack_from("<HHH", raw, base + 2 + i * 6) for i in range(1922)]
    flat = [v for t in tris for v in t]
    body = header("""Part 005 -- the mesh triangle list.

  A 32 x 32 vertex grid (indices 0..1023) triangulated into 1,922 triangles:
  each of the 31 x 31 quads becomes the pair

      (n, n+1, n+32)  and  (n+1, n+33, n+32)

  The list is compiled in rather than generated, so the renderer walks it
  directly. DS:$0002 .. $2D0D.""")
    body += fmt("MeshTris", "array[1..1922, 1..3] of Word", flat, 12, group=3)
    OUT.joinpath("P5MESH.INC").write_text(body + "\n", encoding="ascii")
    return len(flat)


# ---------------------------------------------------------------- part 006

def pascal_strings(raw, base, first, stride, limit=400):
    out, off = [], first
    while len(out) < limit:
        n = raw[base + off]
        if n == 0 or n > 80:
            break
        out.append(raw[base + off + 1: base + off + 1 + n].decode("latin1"))
        off += stride
    return out


def emit_p006_text():
    raw, base = dg("006")
    lines = pascal_strings(raw, base, 0x0D8A, 0x0100)
    body = header(f"""Part 006 -- the credit text, {len(lines)} lines of 12 characters.

  A Borland `array[1..{len(lines)}] of String` -- 256 bytes per element, which is why
  the stride in DGROUP is $100. DS:$0D8A onward.

  Four blocks, one per member: EzE, GoTH, Denthor and Fubar.""")
    body += "  Credits : array[1..%d] of String[12] = (\n" % len(lines)
    for i, s in enumerate(lines):
        comma = "," if i + 1 < len(lines) else ""
        body += f"    '{s.replace(chr(39), chr(39) * 2)}'{comma}\n"
    body += "  );\n"
    OUT.joinpath("P6TEXT.INC").write_text(body, encoding="ascii")
    return len(lines)


def emit_p006_cells():
    """The whoosh board: array[1..26, 1..16, 1..8] of Byte.

    Stored [band][column][rowInBand]; each band is one 8-wide x 16-tall letter
    lying on its side, because the board is drawn transposed (map row -> screen
    X, map column -> screen Y).
    """
    raw, base = dg("006")
    A = 0x000A
    vals = list(raw[base + A: base + A + 26 * 128])
    body = header("""Part 006 scene 2 -- the whoosh board.

  array[1..26, 1..16, 1..8] of Byte, DS:$000A. Each band is one letter cell
  block; the value is the CELL TYPE drawn at that grid position (1 = letter,
  0 = nothing; Whoosh_Load pre-fills the whole board with 2 = background).

  The storage is [band][column][rowInBand], and the board is drawn transposed
  -- map row becomes screen X, map column becomes screen Y -- so each band is
  an 8-wide by 16-tall letter lying on its side.

  Bands  1..16 spell "ASPHYXIA RULZ" (13 letters then 3 blanks) and are the
                only ones Whoosh_Load copies onto the board.
  Bands 17..26 spell "0,000 DOTS" and are NEVER USED -- dead data left in the
                executable. The scroll text boasts "4000 DOTS", so this was
                presumably an earlier version of the same gag.""")
    body += fmt("WhooshBoard", "array[1..26, 1..16, 1..8] of Byte", vals, 32, group=(16, 8))
    OUT.joinpath("P6CELL.INC").write_text(body + "\n", encoding="ascii")
    return len(vals)


# ---------------------------------------------------------------- part 003

def emit_p003_captions():
    raw, base = dg("003")
    lines = pascal_strings(raw, base, 0x76B8, 0x0100)
    body = header(f"""Part 003 scene 7 -- the member captions, {len(lines)} lines of 50 characters.

  array[1..{len(lines)}] of String, DS:$76B8, stride $100. Ten lines per member, in
  the same order as the four rotating portraits.""")
    body += "  Captions : array[1..%d] of String[50] = (\n" % len(lines)
    for i, s in enumerate(lines):
        comma = "," if i + 1 < len(lines) else ""
        body += f"    '{s}'{comma}\n"
    body += "  );\n"
    OUT.joinpath("P3CAPT.INC").write_text(body, encoding="ascii")
    return len(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    results = [
        ("P1VECT.INC", emit_p001(), "values"),
        ("P2OBJ.INC", emit_p002(), "values"),
        ("P5MESH.INC", emit_p005(), "values"),
        ("P6TEXT.INC", emit_p006_text(), "strings"),
        ("P6CELL.INC", emit_p006_cells(), "bytes"),
        ("P3CAPT.INC", emit_p003_captions(), "strings"),
    ]
    for name, n, unit in results:
        p = OUT / name
        print(f"  {name:<14} {n:>7,} {unit:<8} {len(p.read_text(encoding="ascii", errors="replace").splitlines()):>6,} lines")


if __name__ == "__main__":
    main()
