"""Extract NEUROSIS.009's sign-off screen out of the binary.

IMAGEDATA is a 4,000-byte typed constant at DGROUP+2 -- an 80x25 text screen
with attributes, per the debug info (docs/30-byebye.md). DGROUP is segment
$00C3 of the load image; the debug info's own segment table says so, and the
symbol table puts IMAGEDATA at 00C3:0002.

    python tools/emit_byebye.py

writes src/gen/P9IMG.INC -- ASCII, CRLF, a complete typed-constant
declaration ready for {$I}.
"""
import struct
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
B = (ROOT / "bin" / "NEUROSIS.009").read_bytes()

cparhdr = struct.unpack_from("<H", B, 8)[0]
DGROUP = cparhdr * 16 + 0x00C3 * 16
data = B[DGROUP + 2: DGROUP + 2 + 4000]
assert len(data) == 4000

lines = [
    "{ NEUROSIS.009's sign-off screen -- 80x25 characters with attributes,",
    "  read straight out of bin/NEUROSIS.009 at DGROUP+2 (00C3:0002 in the",
    "  debug info, which also names it: IMAGEDATA, 4,000 bytes).",
    "",
    "  Generated by tools/emit_byebye.py -- do not edit. }",
    "",
    "const",
    "  ImageData : array[1..ImageData_Length] of Byte = (",
]
for i in range(0, 4000, 16):
    chunk = ", ".join("%3d" % b for b in data[i:i + 16])
    sep = ");" if i + 16 >= 4000 else ","
    lines.append("    " + chunk + sep)

out = "\r\n".join(lines) + "\r\n"
out.encode("ascii")  # guard: refuse rather than mojibake a DOS file
with open(ROOT / "src" / "gen" / "P9IMG.INC", "w", encoding="ascii",
          newline="") as fh:
    fh.write(out)
print("src/gen/P9IMG.INC: 4000 bytes as %d lines" % len(lines))
