"""A host mirror of src/dos/MKDAT.PAS, so the DOS program can be checked.

WHY A SECOND IMPLEMENTATION EXISTS, which is normally a smell. MKDAT.PAS runs
under real-mode DOS and nothing on the host can run it, so without a mirror the
only way to find out whether the manifest is right is to boot DOSBox -- and the
manifest has to be right before a part can be repointed at the constants it
generates. This produces the same two outputs from the same manifest, byte for
byte, so:

  * the blob can be compared against bin/NEUROSIS.DAT here and now;
  * src/gen/DATOFS.INC can be generated and committed, letting the parts be
    repointed and the ten byte-identical binaries re-verified;
  * and when MKDAT does run, its own output can be diffed against this one.
    If they differ, ONE OF THE TWO IS WRONG and the diff says where.

THE MIRROR IS NOT THE AUTHORITY. MKDAT.PAS is what builds the shipped blob; this
exists to check it and to unblock the host-side work. Where they disagree, the
Pascal is what has to be believed about the blob and this file is what has to
change -- with one exception: if the mirror's blob matches the 1994 file and
MKDAT's does not, the manifest is fine and the Pascal has the bug.

    .venv/Scripts/python.exe tools/mkdat_mirror.py            # write both
    .venv/Scripts/python.exe tools/mkdat_mirror.py --check     # verify only
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MAN = ROOT / "assets/NEUROSIS.MAN"
REF = ROOT / "bin/NEUROSIS.DAT"
INC = ROOT / "src/gen/DATOFS.INC"
VERSION = "MKDAT 1.0"
NAME_COL = 20


def read_manifest(path):
    rows = []
    for line in path.read_text(encoding="ascii").splitlines():
        s = line.strip()
        if not s or s.startswith(";"):
            continue
        parts = s.split()
        if len(parts) >= 2:
            rows.append((parts[0], parts[1]))
    return rows


def pad(s, w):
    return s + " " * max(0, w - len(s))


def build(rows, base):
    """Concatenate, and return (blob, [(const, offset, size)])."""
    blob = bytearray()
    out = []
    for const, dospath in rows:
        f = base / dospath.replace("\\", "/")
        if not f.exists():
            raise SystemExit("the manifest names a file that is not there: %s"
                             % dospath)
        data = f.read_bytes()
        out.append((const, len(blob), len(data)))
        blob += data
    return bytes(blob), out


def render_inc(entries, total, manname):
    L = [
        "{ GENERATED BY %s -- DO NOT EDIT." % VERSION,
        "",
        "  Offsets and lengths of every file in NEUROSIS.DAT, from",
        "  %s. Rebuild both together: an offset" % manname,
        "  here that does not match the blob is a part reading the",
        "  wrong bytes, and it will not announce itself.",
        "",
        "  EVERY CONSTANT HERE IS UNTYPED, ON PURPOSE. An untyped",
        "  constant is a compile-time value folded into the code at",
        "  the point of use, so it costs no storage and this file can",
        "  be included by a unit that uses none of it. Giving one a",
        "  type -- `X : LongInt = $02AEE0` -- would allocate four",
        "  initialised bytes in DGROUP instead, move every variable",
        "  after it and change the data image of every part that",
        "  included this. Do not add a type. }",
        "",
        "const",
    ]
    for const, off, size in entries:
        L.append("  %s= $%06X;" % (pad(const, NAME_COL), off))
        L.append("  %s= %d;" % (pad(const + "_LEN", NAME_COL), size))
    L.append("")
    L.append("  { %d files, %d bytes. }" % (len(entries), total))
    return "\r\n".join(L) + "\r\n"


def main(argv):
    rows = read_manifest(MAN)
    blob, entries = build(rows, MAN.parent)
    ref = REF.read_bytes()

    print("%s (mirror) -- %d files, %d bytes" % (VERSION, len(rows), len(blob)))
    if blob == ref:
        print("  IDENTICAL to bin/NEUROSIS.DAT, all %d bytes." % len(blob))
    else:
        if len(blob) != len(ref):
            print("  DIFFERS: %d bytes against %d" % (len(blob), len(ref)))
        else:
            at = next(i for i in range(len(ref)) if blob[i] != ref[i])
            print("  DIFFERS: first at $%06X" % at)
        return 1

    text = render_inc(entries, len(blob), MAN.name)
    if "--check" in argv:
        cur = INC.read_bytes().decode("ascii") if INC.exists() else ""
        print("  include %s" % ("matches" if cur == text else "WOULD CHANGE"))
        return 0 if cur == text else 1
    INC.write_bytes(text.encode("ascii"))
    print("  wrote %s -- %d constants"
          % (INC.relative_to(ROOT).as_posix(), len(entries) * 2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
