"""Build NEUROSIS.DAT from its manifest, and emit the offsets as Pascal constants.

The blob has no directory. Its structure lived only in hardcoded `Seek` constants
spread across seven programs -- the same offsets written out repeatedly, where
moving any file silently invalidates every offset after it. The reads still
succeed; they return the wrong bytes.

    assets/NEUROSIS.MAN     the ordered list of files, and NOTHING else
    src/gen/DATOFS.INC      generated: every file's offset and length
    tools/mkmanifest.py     regenerates the manifest from the recovered map

THE MANIFEST HOLDS THE ORDER AND NOT THE OFFSETS. Offsets follow from the order
and the file lengths, so putting them in the manifest would be a second copy of a
derived fact, and a second copy can disagree. This computes them.

THE CONSTANTS ARE UNTYPED, WHICH IS WHAT MAKES THEM FREE, and it is measured
rather than assumed: an untyped constant is a compile-time value folded into the
instruction stream, so a unit can include all 170 and use two. Part 001 is
repointed at four of them and all ten targets still rebuild byte-identical, with
its data image unchanged. A TYPED constant -- `X : LongInt = $02AEE0` -- would
allocate four initialised bytes in DGROUP, move every variable after it and
change the data image of every part that included the file. Never emit a type.

    python tools/mkdat.py            build the blob and the include
    python tools/mkdat.py --check    verify both without writing
    python tools/mkdat.py --out DIR [--out DIR2]   also write the blob there

`--out` exists for the packaging step, which needs the blob as a FILE beside the
parts that read it. Note what it does not do: it does not copy bin/NEUROSIS.DAT.
The demo's data is built from assets/ through this manifest every time, so a
packaged demo contains no byte this repository cannot regenerate -- and the
comparison above proves the two are the same 1,718,189 bytes.

WHY THIS IS PYTHON AND NOT A DOS PROGRAM. It was written as `src/dos/MKDAT.PAS`
first, on the reasoning that a tool which builds one of the demo's inputs belongs
in the demo's own toolchain. That was the wrong instinct twice over. Nothing about
concatenating files needs a 1994 compiler, and making it real-mode DOS bought a
16-bit segment limit, 8.3 filenames and an untestable build step -- the Pascal
could not be run from the host at all, so a second implementation had to exist
just to check it. Two implementations of one job, one of them unrunnable here.

The 8.3 asset names stay, and they are now a CONVENTION rather than a constraint:
the tree is read by this script, but NEUROSIS.DAT itself is read by real-mode DOS
programs, and a consistent naming rule across everything that ships is worth
keeping. If that ever stops being true, the names are free to grow.

The rule this leaves behind: reach for the period toolchain when the OUTPUT has
to be period-exact, not when the input happens to be old.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MAN = ROOT / "assets/NEUROSIS.MAN"
REF = ROOT / "bin/NEUROSIS.DAT"
BLOB = ROOT / "bin/NEUROSIS.DAT"
INC = ROOT / "src/gen/DATOFS.INC"
NAME_COL = 20


def read_manifest(path):
    rows = []
    for line in path.read_text(encoding="ascii").splitlines():
        s = line.strip()
        if not s or s.startswith(";"):
            continue
        parts = s.split()
        if len(parts) >= 2:
            rows.append((parts[0], parts[1]))
    return rows


def pad(s, w):
    return s + " " * max(0, w - len(s))


def build(rows, base):
    """Concatenate in manifest order. Returns (blob, [(const, offset, size)])."""
    blob = bytearray()
    out = []
    for const, dospath in rows:
        f = base / dospath.replace("\\", "/")
        if not f.exists():
            raise SystemExit("the manifest names a file that is not there: %s"
                             % dospath)
        data = f.read_bytes()
        out.append((const, len(blob), len(data)))
        blob += data
    return bytes(blob), out


def render_inc(entries, total, manname):
    L = [
        "{ GENERATED BY tools/mkdat.py -- DO NOT EDIT.",
        "",
        "  Offsets and lengths of every file in NEUROSIS.DAT, from",
        "  %s. Rebuild both together: an offset" % manname,
        "  here that does not match the blob is a part reading the",
        "  wrong bytes, and it will not announce itself.",
        "",
        "  EVERY CONSTANT HERE IS UNTYPED, ON PURPOSE. An untyped",
        "  constant is a compile-time value folded into the code at",
        "  the point of use, so it costs no storage and this file can",
        "  be included by a unit that uses none of it. Giving one a",
        "  type -- `X : LongInt = $02AEE0` -- would allocate four",
        "  initialised bytes in DGROUP instead, move every variable",
        "  after it and change the data image of every part that",
        "  included this. Do not add a type. }",
        "",
        "const",
    ]
    for const, off, size in entries:
        L.append("  %s= $%06X;" % (pad(const, NAME_COL), off))
        L.append("  %s= %d;" % (pad(const + "_LEN", NAME_COL), size))
    L.append("")
    L.append("  { %d files, %d bytes. }" % (len(entries), total))
    return "\r\n".join(L) + "\r\n"


def main(argv):
    check = "--check" in argv
    # REPEATABLE: the blob is needed in more than one place at once. run/ is
    # where the scene harnesses are tested and every one of them reads it;
    # dist/ is the packaged demo. Neither is a copy of bin/NEUROSIS.DAT -- both
    # are built here from the manifest, which is the whole point.
    outs = [pathlib.Path(argv[i + 1]) for i, a in enumerate(argv)
            if a == "--out" and i + 1 < len(argv)]
    if "--out" in argv and not outs:
        print("  --out needs a directory")
        return 2
    rows = read_manifest(MAN)
    blob, entries = build(rows, MAN.parent)
    ref = REF.read_bytes() if REF.exists() else None

    print("%d files, %d bytes" % (len(rows), len(blob)))

    # THE COMPARISON IS THE CHECK THAT MATTERS. A manifest in the wrong ORDER
    # produces a blob of exactly the right LENGTH that every part then misreads,
    # so length is not evidence and this is.
    if ref is None:
        print("  no bin/NEUROSIS.DAT to compare against")
    elif blob == ref:
        print("  IDENTICAL to bin/NEUROSIS.DAT, all %d bytes." % len(blob))
    else:
        if len(blob) != len(ref):
            print("  DIFFERS: %d bytes against %d" % (len(blob), len(ref)))
        else:
            at = next(i for i in range(len(ref)) if blob[i] != ref[i])
            print("  DIFFERS: first at $%06X" % at)
        return 1

    text = render_inc(entries, len(blob), MAN.name)
    cur = INC.read_bytes().decode("ascii") if INC.exists() else ""
    if check:
        print("  include %s" % ("matches" if cur == text else "WOULD CHANGE"))
        return 0 if cur == text else 1
    if cur != text:
        INC.write_bytes(text.encode("ascii"))
        print("  wrote %s -- %d constants"
              % (INC.relative_to(ROOT).as_posix(), len(entries) * 2))
    else:
        print("  %s unchanged" % INC.relative_to(ROOT).as_posix())
    # The blob is only written when it would differ, so a routine run does not
    # touch a 1.7 MB tracked file for nothing.
    if ref != blob:
        BLOB.write_bytes(blob)
        print("  wrote %s" % BLOB.relative_to(ROOT).as_posix())
    for out in outs:
        out.mkdir(parents=True, exist_ok=True)
        (out / "NEUROSIS.DAT").write_bytes(blob)
        print("  wrote %s/NEUROSIS.DAT -- %d bytes, built from the manifest"
              % (out.as_posix(), len(blob)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
