"""Generate assets/NEUROSIS.MAN, the build manifest MKDAT.PAS consumes.

WHY THIS IS GENERATED AND NOT HAND-WRITTEN. The manifest is an ordered list of
every file in NEUROSIS.DAT, and the order and the offsets are not ours to
choose: they are recovered from the Seek/BlockRead constants in the seven parts
(see tools/datmap.py and docs/04-neurosis-dat.md). Typing that list by hand
would be a second copy of a fact that already has one home, and the two would
drift the first time a region was renamed.

So this reads the same RECORDS map the carver reads, walks it in file order, and
names each entry after the asset the carver wrote. Run it after any change to
datmap.RECORDS or build_assets.NAMES, then run MKDAT to rebuild the blob.

WHAT IT CHECKS BEFORE WRITING. Every entry must name a file that exists, whose
length equals the BlockRead size the map records, and whose bytes equal that
slice of the original NEUROSIS.DAT. If any of those fails there is no manifest
worth writing, so it refuses and says which entry. That check is the reason the
generated blob can be trusted before anybody runs the DOS program.

    .venv/Scripts/python.exe tools/mkmanifest.py            # write it
    .venv/Scripts/python.exe tools/mkmanifest.py --check     # verify only
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from datmap import RECORDS                        # noqa: E402
from build_assets import NAMES, EXTS              # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
DAT = ROOT / "bin/NEUROSIS.DAT"
OUT = ROOT / "assets/NEUROSIS.MAN"
PAL, SCREEN = 768, 64000


def entries():
    """(constant, part, dospath, offset, size) in file order."""
    out = []
    for part, host, seek, sizes in sorted(RECORDS, key=lambda r: r[2]):
        pos = seek
        for i, size in enumerate(sizes):
            stem = NAMES.get((seek, i)) or "%06X%s" % (seek, chr(65 + i))
            ext = EXTS.get((seek, i))
            if ext is None:
                ext = ".PAL" if size == PAL else (
                    ".RAW" if size == SCREEN else ".BIN")
            out.append(("DAT_P%s_%s" % (part[-1], stem), part,
                        "PART%s\\%s%s" % (part, stem, ext), pos, size))
            pos += size
    return out


def verify(rows):
    blob = DAT.read_bytes()
    bad = []
    seen = {}
    for const, part, dospath, off, size in rows:
        if const in seen:
            bad.append("%s is used twice (%s and %s)"
                       % (const, seen[const], dospath))
        seen[const] = dospath
        path = ROOT / "assets" / dospath.replace("\\", "/")
        if not path.exists():
            bad.append("%s: no such file" % dospath)
            continue
        data = path.read_bytes()
        if len(data) != size:
            bad.append("%s: %d bytes, the map says %d"
                       % (dospath, len(data), size))
        elif data != blob[off:off + size]:
            bad.append("%s: content differs from NEUROSIS.DAT at $%06X"
                       % (dospath, off))
    total = sum(r[4] for r in rows)
    if total != len(blob):
        bad.append("the manifest totals %d bytes, NEUROSIS.DAT is %d"
                   % (total, len(blob)))
    return bad, total


def render(rows, total):
    w = max(len(r[0]) for r in rows)
    lines = [
        "; NEUROSIS.DAT build manifest -- GENERATED by tools/mkmanifest.py.",
        ";",
        "; Every file in the blob, in file order. MKDAT.PAS concatenates them in",
        "; the order below, which is the only order that reproduces the 1994",
        "; file: the parts Seek to absolute offsets, so a manifest in any other",
        "; order builds a blob every one of them reads wrong.",
        ";",
        "; The offsets are NOT in this file on purpose. They are a consequence of",
        "; the order and the sizes, so MKDAT computes them and emits them as",
        "; constants -- one fact, one home. What is here is the order.",
        ";",
        "; %d files, %d bytes." % (len(rows), total),
        "; Verified against bin/NEUROSIS.DAT, byte for byte, when generated.",
        ";",
        "; <constant>%s<file>" % (" " * (w - 9)),
    ]
    part = None
    for const, p, dospath, off, size in rows:
        if p != part:
            lines.append(";")
            lines.append("; ---- part %s ----" % p)
            part = p
        lines.append("%-*s  %s" % (w, const, dospath))
    return "\n".join(lines) + "\n"


def main(argv):
    rows = entries()
    bad, total = verify(rows)
    if bad:
        print("REFUSED: the manifest does not reproduce NEUROSIS.DAT")
        for b in bad:
            print("   ", b)
        return 1
    print("%d entries, %d bytes, every one verified against bin/NEUROSIS.DAT"
          % (len(rows), total))
    if "--check" in argv:
        return 0
    OUT.write_text(render(rows, total), encoding="ascii", newline="\r\n")
    print("wrote %s" % OUT.relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
