"""Generate a test program per scene unit.

The point of splitting the parts into scene units was to be able to run each
piece on its own. That only helps if the harnesses exist, so they are
generated rather than written by hand -- one per scene, all identical apart
from the unit and entry point.

    python tools/mktests.py                write them all
    python tools/dosbox/dosbuild.py TESTP1S3   build one

Each needs NEUROSIS.DAT in the current directory, so run them from run/.
"""
import pathlib

SRC = pathlib.Path("src")

# unit, entry point, what it is
# unit, entry point, TEST PROGRAM NAME (8.3! max eight characters), description
SCENES = [
    ("P1S1",     "Scene1", "TP1S1",  "part 001 scene 1 -- logo and bouncing lenses"),
    ("P1S2",     "Scene2", "TP1S2",  'part 001 scene 2 -- "ASPHYXIA PRESENTS" and the comet'),
    ("P1S3",     "Scene3", "TP1S3",  "part 001 scene 3 -- mosaic pixelate"),
    ("P1S4",     "Scene4", "TP1S4",  "part 001 scene 4 -- rotating 3-D text"),
    ("P1S5",     "Scene5", "TP1S5",  "part 001 scene 5 -- vector objects and wipe"),
    ("P3TUNNEL", "Scene1", "TP3TUN", "part 003 scene 1 -- the tunnel"),
    ("P3STARS",  "Scene2", "TP3STR", "part 003 scene 2 -- the star tube"),
    ("P3MORPH",  "Scene3", "TP3MOR", "part 003 scene 3 -- the morph"),
    ("P3GLOBE",  "Scene4", "TP3GLB", "part 003 scene 4 -- the globe"),
    ("P3BLOCKS", "Scene5", "TP3BLK", "part 003 scene 5 -- the blocks"),
    ("P3WAVES",  "Scene6", "TP3WAV", "part 003 scene 6 -- the waves"),
    ("P3SPRITE", "Scene7", "TP3SPR", "part 003 scene 7 -- the spinning portraits"),
]

TEMPLATE = '''{ ===========================================================================
  Test harness for %(what)s.

  One scene on its own: if it misbehaves the fault is in %(unit)s or in the VGA
  unit beneath it, and nowhere else. Generated by tools/mktests.py -- do not
  edit; change the generator instead.

  Needs NEUROSIS.DAT in the current directory, so run it from run\\.

  Build:  python tools/dosbox/dosbuild.py %(prog)s
  =========================================================================== }

program %(prog)s;

uses Crt, VGA, DemoVT, %(unit)s;

var
  F : file;
begin
  Assign(F, 'neurosis.dat');
  {$I-} Reset(F, 1); {$I+}
  if IOResult <> 0 then
  begin
    WriteLn('%(prog)s: neurosis.dat not found in the current directory.');
    WriteLn('          Run this from the run\\ folder.');
    Halt(1);
  end;
  Close(F);

  WriteLn('%(what)s');
  WriteLn('Press a key to start, and any key again to stop.');
  ReadKey;

  SetMode13h;
  VirtScrAlloc;
  MusicInit;          { harmless with no player resident }

  %(entry)s;

  VirtScrFree;
  SetTextMode;
  WriteLn('Done.');
end.
'''

names = []
for unit, entry, prog, what in SCENES:
    (SRC / (prog + ".PAS")).write_text(
        TEMPLATE % dict(prog=prog, unit=unit, entry=entry, what=what))
    names.append((prog, unit))
    print("  %-14s -> %s" % (prog + ".PAS", unit))

print("
  %d harnesses written. tools/dosbox/dosbuild.py keeps its own NAMES
"
      "  and HARNESS tables -- add new scenes to both." % len(names))
