"""Lift part 002 scene 2's four objects out of DGROUP into a Pascal include.

Scene2_Setup (108b:1bbd) builds each object from two compiled-in word tables:
a vertex table of integer triples and a face table walked with a running
cursor. Both are initialised data, so they are in the file image and can be
read straight out rather than transcribed by hand.

THE FOUR OBJECTS ARE NOT BUILT THE SAME WAY. Scene2_Setup has four separate
copies of the loop and object 1's differs from the other three in two places.
Treating them alike is what made the pistol hang faces off the top-left corner
and the sailboat cover the screen: adding one to an already-one-based index
walks off the end of a 68-entry vertex array into whatever follows it.

  vertex components   ALL FOUR are halved before becoming 16.16 fixed point
                      (108b:1d1d, 1ef5, 20cb, 22a6 -- `CWD / MOV CX,2 / IDIV`)

  face vertex index   object 1 ONLY is stored PLUS ONE (the `INC AX` at
                      108b:1df6). Objects 2, 3 and 4 store the table value
                      unchanged (108b:1fca, 21a0, 237b -- the word is loaded
                      straight into DX), so their tables are already 1-based.

  face colour         object 1 reads a WORD and halves it (108b:1e14).
                      Objects 2, 3 and 4 read a BYTE and do not halve
                      (108b:1fee, 21c4, 239f -- `MOV AL, byte ptr [...]`).

Run:  python tools/p2obj.py    ->  src/gen/P2OBJ.INC
"""
import pathlib
import struct
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from mzinfo import parse

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXE = ROOT / "work" / "split" / "NEUROSIS_002_fpu.exe"

# name, vertex count, vertex table, face count, face table,
# index bias, halve the colour
OBJECTS = [
    ("Enterprise", 75, 0x0004, 55, 0x01C6, 1, True),
    ("Revolver",   68, 0x067E, 64, 0x0816, 0, False),
    ("Sailboat",   32, 0x0B06, 21, 0x0BC6, 0, False),
    ("Quad",        4, 0x0CAE,  1, 0x0CC6, 0, False),
]

MAXVERTS = 8          # a face record has room for eight indices


def main():
    h = parse(EXE)
    raw = h["raw"]
    ds = h["hdrsize"] + 0x0866 * 16

    def word(off):
        return struct.unpack("<h", raw[ds + off:ds + off + 2])[0]

    out = [
        "{ ===========================================================",
        "  Generated by tools/p2obj.py -- do not edit.",
        "",
        "  The four objects of NEUROSIS.002 scene 2, read out of DGROUP:",
        "  the Enterprise, a revolver, a sailboat and a single quad.",
        "",
        "  Scene2_Setup (108b:1bbd) builds each one slightly differently and",
        "  the differences are already applied here. Vertex components are",
        "  halved for all four. Only the Enterprise's face indices are biased",
        "  by one and only its colours are halved; the other three tables are",
        "  already one-based and their colours are raw bytes.",
        "  =========================================================== }",
        "",
        "const",
    ]

    for name, nv, vtab, nf, ftab, bias, halve in OBJECTS:
        verts = []
        for i in range(nv):
            verts.append(tuple(word(vtab + (i * 3 + k) * 2) // 2
                               for k in range(3)))

        faces = []
        cur = 0
        over = 0
        for _ in range(nf):
            cnt = word(ftab + cur * 2)
            cur += 1
            idx = []
            for _k in range(cnt):
                v = word(ftab + cur * 2) + bias
                if v < 1 or v > nv:
                    over += 1
                idx.append(v)
                cur += 1
            raw_col = word(ftab + cur * 2)
            colour = (raw_col // 2) if halve else (raw_col & 0xFF)
            cur += 1
            faces.append((cnt, idx, colour))
        if over:
            print("  !! %s: %d vertex index/indices outside 1..%d"
                  % (name, over, nv))

        out.append("  %sVertCount = %d;" % (name, nv))
        out.append("  %sFaceCount = %d;" % (name, nf))
        out.append("  %sVerts : array[1..%d, 1..3] of Integer = ("
                   % (name, nv))
        rows = ["    (%6d, %6d, %6d)" % v for v in verts]
        out.append(",\n".join(rows))
        out.append("  );")
        out.append("  { count, eight indices, colour }")
        out.append("  %sFaces : array[1..%d, 0..%d] of Integer = ("
                   % (name, nf, MAXVERTS + 1))
        rows = []
        for cnt, idx, colour in faces:
            padded = idx + [0] * (MAXVERTS - len(idx))
            rows.append("    (%2d, %s, %3d)"
                        % (cnt, ", ".join("%3d" % v for v in padded), colour))
        out.append(",\n".join(rows))
        out.append("  );")
        out.append("")

        print("  %-6s %3d verts, %3d faces, face table %d words"
              % (name, nv, nf, cur))

    gen = ROOT / "src" / "gen"
    gen.mkdir(parents=True, exist_ok=True)
    (gen / "P2OBJ.INC").write_text("\n".join(out) + "\n", encoding="ascii")
    print("  wrote src/gen/P2OBJ.INC (%d lines)" % len(out))


if __name__ == "__main__":
    main()
